/* Generated by tools/cull-companies.py. Do not edit by hand.
 * 50 pre-IPO companies. PreStocks is index 0 and its mark is
 * prestocks.com own apple-icon.png; the other 49 were scraped
 * from forgeglobal.com/search-companies by fetch-forge-logos.py
 * and culled from 119 to the ones people have heard of.
 * "f" is the basename under logos/ and deploy/logos/, and it is
 * always the row index: Scripts/main.gd builds the path from the
 * index, so the two can never be allowed to drift.
 * Company names and marks are their owners trademarks; they
 * appear here nominatively, to name the company they identify. */
window.AGARIPO_LOGOS = [{"n":"PreStocks","f":"000"},{"n":"OpenAI","f":"001"},{"n":"Anthropic","f":"002"},{"n":"SpaceX","f":"003"},{"n":"xAI","f":"004"},{"n":"Stripe","f":"005"},{"n":"Databricks","f":"006"},{"n":"Anduril","f":"007"},{"n":"ByteDance","f":"008"},{"n":"Discord","f":"009"},{"n":"Epic Games","f":"010"},{"n":"Canva","f":"011"},{"n":"Revolut","f":"012"},{"n":"Ripple","f":"013"},{"n":"Kraken","f":"014"},{"n":"Polymarket","f":"015"},{"n":"Kalshi","f":"016"},{"n":"Chainalysis","f":"017"},{"n":"Perplexity","f":"018"},{"n":"Neuralink","f":"019"},{"n":"Blue Origin","f":"020"},{"n":"Waymo","f":"021"},{"n":"DJI","f":"022"},{"n":"Valve","f":"023"},{"n":"OnlyFans","f":"024"},{"n":"Plaid","f":"025"},{"n":"Deel","f":"026"},{"n":"Rippling","f":"027"},{"n":"Ramp","f":"028"},{"n":"Mercury","f":"029"},{"n":"Vercel","f":"030"},{"n":"Replit","f":"031"},{"n":"Hugging Face","f":"032"},{"n":"Mistral AI","f":"033"},{"n":"DeepSeek","f":"034"},{"n":"Cohere","f":"035"},{"n":"Scale AI","f":"036"},{"n":"Groq","f":"037"},{"n":"Cerebras","f":"038"},{"n":"Figure AI","f":"039"},{"n":"Zipline","f":"040"},{"n":"Skydio","f":"041"},{"n":"Flexport","f":"042"},{"n":"Whoop","f":"043"},{"n":"OURA","f":"044"},{"n":"Strava","f":"045"},{"n":"Fanatics","f":"046"},{"n":"The Boring Company","f":"047"},{"n":"Beast Industries","f":"048"},{"n":"Suno","f":"049"}];
